### ISSUE TITLE
How to build less to css in production mode

### ISSUE THREAD

**Issue by kartikag01** [ryouaki/react-less-watcher#2]
On the server, when we create build, there are no CSS files, as they are in git ignore.
How to build less to CSS in production mode?

**Comment by ryouaki** [comment]
The less files are built to css when you are coding, so you do not need build less again.

**Comment by kartikag01** [comment]
As CSS files are build files, i was considering not to put them in git.
The issue is solved, I have used.
```

"build-css": "node-less-chokidar src",   
"build": "npm run build-css & react-scripts build",
```

**Comment by luc-plamondon** [comment]
I had the same problem, @KARTIK01's answer is really valuable but it is not easy to find. I kindly suggest the author adds this "build" task to the main doc, after "watch-less" and "start": 

scripts: {
    "watch-less": "react-less-watcher -d src",
    "start": "react-scripts start&npm run watch-less"
    "build": "npm run watch-less & react-scripts build"
  }

I, too, prefer not to commit files that are automatically generated. Therefore, when deploying from a freshly checked out project, "build" task should not assume that "start" has been run before.

By the way, @ryouaki, thank you so much for this package, it is by far the simplest solution I have found!

**Comment by ryouaki** [comment]
@luc-plamondon Thank you for your suggestion,  This is a good idea ,I will do it soon. But direct exec command "npm run watch-less & react-scripts build" will not work well, because watch-less will create a monitor to see if less file is changed until you cancel it by yourself.

so I think I can add an argument for build less only once.

**Comment by luc-plamondon** [comment]
I see. Should I use @KARTIK01 solution, then?

**Comment by ryouaki** [comment]
> I see. Should I use @KARTIK01 solution, then?

Yes, it is ok.
